id: P5EB4CB4F
initial_creation_type: input
source_metadata:
  title: Replies to Questions
  language: en
  description: 'A selection of replies, responses or answers to questions (dris lan):'
  volume:
    6ee5eb15cc3841b28bedfb43cdbb8665:
      title: Advice for Hor Özer
      parent: General
    fb375ba293af4983bd3c954bdf58806a:
      title: Khandro's Plea
      parent: General
    17d1dccdd36c4c4aa1191f0ba871a49e:
      title: The Pointing-the-Staff Instruction
      parent: General
created_at: '2022-03-01T05:25:02.267565'
last_modified_at: '2022-03-01T05:25:02.267571'
